### ISSUE TITLE
Short Versions

### ISSUE THREAD

**Issue by djhocking** [ethanwhite/CV#2]
I'm curious if you've found a decent workflow for outputting 1 and 2 page versions of your CV with this? Grants often require this but I haven't figured out an easy way to get it starting in markdown (much easier directly in MS Word [gasp] then save as PDF).

**Comment by ethanwhite** [comment]
I don't have anything that distills this document down. The truth is there are enough differences in grant style biosketches (e.g., inclusion of synergistic activities, conflicts of interest, only selecting 10 publications/products etc.) that what I actually have is a basic biosketch markdown CV that I then tweak for each grant, either adding or removing sections or just switching out products/publications. I have a style sheet for formatting it to NSF specs. I can add some of that material here if it would be useful to see examples.

**Comment by djhocking** [comment]
Thanks, that all makes sense. I would greatly appreciate it if you have an NSF style sheet. I will likely need one in the next month or so for a RAPID proposal. I'm still relatively new to using markdown and creating/modifying style sheets. I assume you just use a little trial and error to get the pdf output to be the desired length (maybe mostly based on number of markdown lines).

**Comment by ethanwhite** [comment]
Actually it looks like I use the same template and style sheet as for my regular CV. I've added the markdown and pdf versions of a recent biosketch as well as added it to the makefile. Yes, for length it's a little trial and error.

**Comment by djhocking** [comment]
This is perfect, thanks again for the help and examples.
